### ISSUE TITLE
Error out of the box

### ISSUE THREAD

**Issue by Noxobar** [XingYuSSS/slurm--#1] opened 2024-11-06 05:15 UTC
Error running command slurm--.refreshing: command 'slurm--.refreshing' not found. This is likely caused by the extension that contributes slurm--.refreshing.

**Comment by XingYuSSS** [comment] 2024-11-06 07:52
Hi! Thank you for reporting this issue. I have reviewed the details and confirmed that this is indeed a bug.

This is because the command `slurm--.refreshing` I defined before was only used to display `refreshing` button without defining its corresponding function. I'm going to remove this useless command, because the button is usually not visible.

I appreciate your patience and the time you took to report this. We are working on a fix, and it will be included in the next release.
If you have any further questions or need more information, please feel free to let me know.

**Closed** 2024-11-06 14:57 UTC

**Comment by XingYuSSS** [comment] 2024-11-06 15:16
hello @Noxobar , I fixed that in version 0.5.1, please update and verify if the issue is resolved =)
